### ISSUE TITLE
Create script to perform hyperparameter scan

### ISSUE THREAD

**Issue by BenGalewsky** [scailfin/madminer-workflow#24]
_As an analyzer I want to try out different hyper parameters and see which ones yield the best result_

# Acceptance Criteria
1. I can run MadMiner MLproject from a script with a collection of parameters to try
2. I can review the results in the MLflow ui

**Comment by Sinclert** [comment]
A couple of PRs has been merged tackling this issue.

Feel free to close this issue (I cannot).
