### ISSUE TITLE
Split workflow into different repos

### ISSUE THREAD

**Issue by Sinclert** [scailfin/madminer-workflow#26]
This repository is currently serving 2 different purposes, and may soon serve a different one:

- **Purpose 1:** Provide a [Docker image](https://github.com/scailfin/workflow-madminer/blob/master/docker-images/docker-madminer-all/Dockerfile) with all the necessary dependencies to run [this Jupyter notebook](https://cranmer.github.io/madminer-tutorial/intro.html).
- **Purpose 2:** Build and publish Docker images ([Physics](https://github.com/scailfin/workflow-madminer/blob/master/docker-images/docker-madminer-physics/Dockerfile) & [ML](https://github.com/scailfin/workflow-madminer/blob/master/docker-images/docker-madminer-ml/Dockerfile)) to run a REANA workflow.
- **Purpose 3 (Soon):** Provide MLFlow parametrization and tracking features to track how trained models perform (only affecting _ML_ part of the workflow).

### Proposal

We could create 3 new repositories:
- `madminer-jupyter-env`: containing [this folder](https://github.com/scailfin/workflow-madminer/tree/master/docker-images/docker-madminer-all)
- `madminer-workflow-ml`: containing [this folder](https://github.com/scailfin/workflow-madminer/tree/master/docker-images/docker-madminer-ml)
- `madminer-workflow-ph`: containing [this folder](https://github.com/scailfin/workflow-madminer/tree/master/docker-images/docker-madminer-physics)

And leave this repository as a convergence point where `madminer-workflow-ml` and `madminer-workflow-ph` are defined as [GIT sub-modules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) (a way of referencing a GIT repository from within a GIT repository).

Example `.gitmodules` files:
```ini
[submodule "madminer-workflow-ml"]
	path = madminer-workflow-ml
	url = git@github.com:scailfin/madminer-workflow-ml.git
	branch = master
[submodule "madminer-workflow-ph"]
	path = madminer-workflow-ph
	url = git@github.com:scailfin/madminer-workflow-ph.git
	branch = master
```

It would also containing the [reana folder](https://github.com/scailfin/workflow-madminer/tree/master/reana) with the joint workflow specification.

---

If _Scailfin_ is not the place to create those repositories, then maybe [DIANA-HEP](https://github.com/diana-hep) (where madminer is hosted), or a brand new organization are better options.

**Comment by irinaespejo** [comment]
Hi @Sinclert, I think it's a great suggestion. The project is growing and the current repo will be too crowded. I tried using git sub-modules to host a separate repo with the docker images but I didn't get it to work properly. With respect to _Scailfin_ vs DIANA-HEP maybe on  the #madminer-on-reana channel they have a better picture on where the repos should go. Thank you for this idea!
